/*
============================================================
ETSY AI SHOPPING DECISION ASSISTANT
Member C — Prototype Builder
============================================================

WHAT THIS PROTOTYPE DEMONSTRATES

This prototype demonstrates an AI-assisted shopping decision
feature for Etsy.

The shopper describes what they are looking for using natural
language. Google Gemini extracts structured shopping criteria
such as recipient, occasion, budget, category, style,
personalization requirements, delivery requirements, and
interests.

The application searches a synthetic dataset containing
100 Etsy-style product listings.

The strongest candidate products are provided to Gemini for
comparison. Gemini selects three recommendations and explains
why they match the shopper's request.

IMPORTANT:
Product facts such as price, rating, delivery time, materials,
and personalization availability come from the structured
dataset rather than being generated by the AI.

This helps reduce hallucinated product information.

LOCAL RUN:

1. npm install

2. Create .env:

   GEMINI_API_KEY=YOUR_GEMINI_API_KEY
   PORT=3000

3. npm start

4. Open:

   http://localhost:3000

RAILWAY:

Add GEMINI_API_KEY as a Railway environment variable.
Railway supplies PORT automatically.

PRODUCTION:

A production implementation would use live Etsy marketplace
data, current prices, current shipping estimates, authentication,
production retrieval infrastructure, monitoring, rate limiting,
and links to real Etsy listings.

The dataset used here is synthetic and is intended only for
academic demonstration.

ChatGPT was used as an AI coding assistant during development.
============================================================
*/


// ============================================================
// IMPORTS
// ============================================================

require("dotenv").config();

const express = require("express");
const path = require("path");
const fs = require("fs");

const { GoogleGenAI } = require("@google/genai");


// ============================================================
// APPLICATION CONFIGURATION
// ============================================================

const app = express();

const PORT = process.env.PORT || 3000;

const GEMINI_API_KEY = process.env.GEMINI_API_KEY;


// ============================================================
// CHECK API KEY
// ============================================================

if (!GEMINI_API_KEY) {
  console.error(
    "ERROR: GEMINI_API_KEY is not configured."
  );

  console.error(
    "Add GEMINI_API_KEY to .env locally or Railway Variables."
  );

  process.exit(1);
}


// ============================================================
// GEMINI
// ============================================================

const ai = new GoogleGenAI({
  apiKey: GEMINI_API_KEY
});

const GEMINI_MODEL = "gemini-3.1-flash-lite";


// ============================================================
// EXPRESS MIDDLEWARE
// ============================================================

app.use(
  express.json({
    limit: "100kb"
  })
);

app.use(
  express.static(
    path.join(__dirname, "public")
  )
);


// ============================================================
// LOAD PRODUCT DATASET
// ============================================================

const DATA_FILE = path.join(
  __dirname,
  "data",
  "synthetic_etsy_listings.json"
);

let products = [];

try {
  const rawData = fs.readFileSync(
    DATA_FILE,
    "utf8"
  );

  products = JSON.parse(rawData);

  if (!Array.isArray(products)) {
    throw new Error(
      "Dataset must contain a JSON array."
    );
  }

  if (products.length === 0) {
    throw new Error(
      "Dataset contains no products."
    );
  }

  console.log(
    `Loaded ${products.length} synthetic Etsy-style listings.`
  );
} catch (error) {
  console.error(
    "Could not load product dataset:",
    error.message
  );

  process.exit(1);
}


// ============================================================
// HELPER: NORMALIZE
// ============================================================

function normalize(value) {
  if (
    value === null ||
    value === undefined
  ) {
    return "";
  }

  if (Array.isArray(value)) {
    return value
      .join(" ")
      .toLowerCase()
      .trim();
  }

  return String(value)
    .toLowerCase()
    .trim();
}


// ============================================================
// HELPER: TOKENIZE
// ============================================================

function tokenize(value) {
  return normalize(value)
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(word => word.length > 1);
}


// ============================================================
// HELPER: UNIQUE VALUES
// ============================================================

function unique(values) {
  return [
    ...new Set(
      values.filter(Boolean)
    )
  ];
}


// ============================================================
// HELPER: CONVERT VALUE TO ARRAY
// ============================================================

function toArray(value) {
  if (Array.isArray(value)) {
    return value;
  }

  if (
    value === null ||
    value === undefined ||
    value === ""
  ) {
    return [];
  }

  return [value];
}


// ============================================================
// BUILD SEARCHABLE PRODUCT TEXT
// ============================================================

function productText(product) {
  if (!product) {
    return "";
  }

  return normalize([
    product.title,
    product.category,
    product.subcategory,
    product.description,

    ...toArray(product.style),
    ...toArray(product.materials),
    ...toArray(product.colors),
    ...toArray(product.recipients),
    ...toArray(product.occasions),
    ...toArray(product.interests),
    ...toArray(product.personalization_options),
    ...toArray(product.review_themes)
  ]);
}


// ============================================================
// SEARCH PRODUCTS
// ============================================================

function searchProducts(
  criteria = {},
  searchTerms = []
) {
  const terms = unique(
    tokenize([
      ...toArray(searchTerms),
      criteria.recipient,
      criteria.occasion,
      criteria.category,
      ...toArray(criteria.style),
      ...toArray(criteria.interests)
    ])
  );

  const scoredProducts = products
    .filter(
      product =>
        product &&
        typeof product === "object"
    )
    .map(product => {
      let score = 0;

      const searchableText =
        productText(product);

      // ------------------------------------------------------
      // KEYWORD MATCHING
      // ------------------------------------------------------

      for (const term of terms) {
        if (
          searchableText.includes(term)
        ) {
          score += 2;
        }
      }


      // ------------------------------------------------------
      // CATEGORY
      // ------------------------------------------------------

      if (criteria.category) {
        const requestedCategory =
          normalize(criteria.category);

        const productCategory =
          normalize([
            product.category,
            product.subcategory
          ]);

        if (
          productCategory.includes(
            requestedCategory
          ) ||
          requestedCategory.includes(
            normalize(product.category)
          )
        ) {
          score += 10;
        }
      }


      // ------------------------------------------------------
      // BUDGET
      // ------------------------------------------------------

      const maxBudget =
        Number(criteria.max_budget);

      const productPrice =
        Number(product.price);

      if (
        Number.isFinite(maxBudget) &&
        maxBudget > 0 &&
        Number.isFinite(productPrice)
      ) {
        if (
          productPrice <= maxBudget
        ) {
          score += 8;
        } else {
          score -= 8;
        }
      }


      // ------------------------------------------------------
      // PERSONALIZATION
      // ------------------------------------------------------

      if (
        criteria.personalization_required === true
      ) {
        if (
          product.personalizable === true
        ) {
          score += 9;
        } else {
          score -= 10;
        }
      }


      // ------------------------------------------------------
      // DELIVERY
      // ------------------------------------------------------

      const maxDelivery =
        Number(
          criteria.max_delivery_days
        );

      const productDelivery =
        Number(
          product.estimated_delivery_days
        );

      if (
        Number.isFinite(maxDelivery) &&
        maxDelivery > 0 &&
        Number.isFinite(productDelivery)
      ) {
        if (
          productDelivery <= maxDelivery
        ) {
          score += 8;
        } else {
          score -= 7;
        }
      }


      // ------------------------------------------------------
      // RECIPIENT
      // ------------------------------------------------------

      if (criteria.recipient) {
        const requestedRecipient =
          normalize(criteria.recipient);

        const productRecipients =
          normalize(product.recipients);

        if (
          productRecipients.includes(
            requestedRecipient
          )
        ) {
          score += 5;
        }
      }


      // ------------------------------------------------------
      // OCCASION
      // ------------------------------------------------------

      if (criteria.occasion) {
        const requestedOccasion =
          normalize(criteria.occasion);

        const productOccasions =
          normalize(product.occasions);

        if (
          productOccasions.includes(
            requestedOccasion
          )
        ) {
          score += 5;
        }
      }


      // ------------------------------------------------------
      // STYLE
      // ------------------------------------------------------

      for (
        const style
        of toArray(criteria.style)
      ) {
        if (
          normalize(product.style)
            .includes(
              normalize(style)
            )
        ) {
          score += 4;
        }
      }


      // ------------------------------------------------------
      // INTERESTS
      // ------------------------------------------------------

      for (
        const interest
        of toArray(criteria.interests)
      ) {
        if (
          searchableText.includes(
            normalize(interest)
          )
        ) {
          score += 4;
        }
      }


      // ------------------------------------------------------
      // RATINGS
      // ------------------------------------------------------

      const rating =
        Number(product.rating);

      if (Number.isFinite(rating)) {
        if (rating >= 4.8) {
          score += 3;
        } else if (rating >= 4.5) {
          score += 2;
        }
      }


      return {
        product,
        score
      };
    });


  scoredProducts.sort(
    (a, b) => {
      if (b.score !== a.score) {
        return b.score - a.score;
      }

      return (
        Number(
          b.product?.rating || 0
        ) -
        Number(
          a.product?.rating || 0
        )
      );
    }
  );


  return scoredProducts
    .slice(0, 20)
    .map(item => item.product)
    .filter(Boolean);
}


// ============================================================
// PARSE GEMINI JSON
// ============================================================

function parseJSONResponse(text) {
  if (!text) {
    throw new Error(
      "Gemini returned an empty response."
    );
  }

  const cleaned = text
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();

  try {
    return JSON.parse(cleaned);
  } catch (error) {
    console.error(
      "Could not parse Gemini response:"
    );

    console.error(cleaned);

    throw new Error(
      "Gemini returned invalid structured data."
    );
  }
}


// ============================================================
// CALL GEMINI
// ============================================================

async function callGemini(
  systemInstruction,
  input
) {
  const maxAttempts = 3;

  for (
    let attempt = 1;
    attempt <= maxAttempts;
    attempt++
  ) {
    try {
      const response =
        await ai.models.generateContent({
          model: GEMINI_MODEL,

          contents: input,

          config: {
            systemInstruction,

            responseMimeType:
              "application/json",

            temperature: 0.2
          }
        });

      if (!response.text) {
        throw new Error(
          "Gemini returned no response."
        );
      }

      return response.text
        .replace(/```json/gi, "")
        .replace(/```/g, "")
        .trim();

    } catch (error) {
      const status =
        Number(
          error.status ||
          error.code
        );

      const temporaryError =
        status === 429 ||
        status === 503;

      if (
        temporaryError &&
        attempt < maxAttempts
      ) {
        console.log(
          `Gemini temporarily unavailable. Retrying ${attempt}/${maxAttempts}...`
        );

        await new Promise(
          resolve =>
            setTimeout(
              resolve,
              attempt * 2000
            )
        );

        continue;
      }

      throw error;
    }
  }

  throw new Error(
    "Gemini request failed."
  );
}


// ============================================================
// PROMPT 1: REQUEST UNDERSTANDING
// ============================================================

const EXTRACTION_PROMPT = `
You are the request-understanding component of the Etsy AI
Shopping Decision Assistant.

Your purpose is to translate a shopper's natural-language
shopping request into structured criteria that can be used
to search Etsy-style product listings.

The feature helps shoppers compare products based on factors
such as:

- recipient
- occasion
- budget
- product category
- style
- personalization
- delivery time
- interests

Extract only information supported by the shopper's request.

NEVER invent preferences that the shopper did not state.

Interpret common shopping language correctly.

Examples:

"under $50"
means max_budget = 50.

"within two weeks"
means max_delivery_days = 14.

"personalized gift"
means personalization_required = true.

"silver minimalist jewelry"
means jewelry is the category and silver/minimalist should
be reflected in the search criteria.

Search terms should contain concise words or phrases that
are useful for finding matching products.

CLARIFICATION:

Ask ONE concise clarifying question only when the request
is too vague to provide meaningful recommendations.

Example:

"I need a gift"

is too vague.

However:

"I need a birthday gift for my mom under $50"

contains enough information to continue.

Return ONLY valid JSON.

Use this exact structure:

{
  "needs_clarification": false,
  "clarifying_question": null,
  "search_terms": [],
  "criteria": {
    "recipient": null,
    "occasion": null,
    "max_budget": null,
    "category": null,
    "style": [],
    "personalization_required": null,
    "max_delivery_days": null,
    "interests": []
  }
}

Do not include Markdown.

Do not include text outside the JSON.
`;


// ============================================================
// PROMPT 2: PRODUCT COMPARISON
// ============================================================

const COMPARISON_PROMPT = `
You are the recommendation and comparison component of the
Etsy AI Shopping Decision Assistant.

You will receive:

1. The shopper's original request.
2. Structured shopping criteria.
3. Candidate product listings retrieved from a structured
   product dataset.

Select exactly THREE of the best candidate products.

The goal is to help the shopper make a decision by comparing
products against the shopper's actual requirements.

IMPORTANT:

All factual product information comes from the supplied
candidate dataset.

NEVER invent or modify:

- listing IDs
- titles
- categories
- prices
- personalization availability
- personalization options
- materials
- colors
- delivery estimates
- ratings
- review counts
- review themes
- product features

Your role is to compare the products and explain their fit.

PRIORITIZATION:

Explicit shopper constraints are more important than general
preferences.

Prioritize:

1. Requested category or product type
2. Maximum budget
3. Required personalization
4. Maximum delivery time
5. Style
6. Recipient
7. Occasion
8. Interests
9. Ratings and reviews

If a product fails an explicit requirement, identify that
requirement in requirements_not_met.

Do not describe a product as a Strong match if it fails an
important hard requirement.

MATCH LEVEL:

Use only:

"Strong"
"Good"
"Partial"

REVIEW INSIGHT:

Only summarize review themes supplied in review_themes.

Never invent customer review information.

Return ONLY valid JSON.

Use this exact structure:

{
  "recommendations": [
    {
      "listing_id": "1",
      "match_level": "Strong",
      "reason": "Brief explanation.",
      "requirements_met": [
        "Requirement"
      ],
      "requirements_not_met": [],
      "review_insight": "Brief grounded review insight."
    }
  ]
}

Return exactly THREE recommendations when at least three
candidate products are available.

Do not include Markdown.

Do not include text outside the JSON.
`;


// ============================================================
// CREATE SAFE PRODUCT RESPONSE
// ============================================================

function buildRecommendation(
  product,
  aiRecommendation = null
) {
  if (!product) {
    return null;
  }

  const allowedMatchLevels = [
    "Strong",
    "Good",
    "Partial"
  ];

  let matchLevel = "Good";

  if (
    aiRecommendation &&
    allowedMatchLevels.includes(
      aiRecommendation.match_level
    )
  ) {
    matchLevel =
      aiRecommendation.match_level;
  }

  return {
    listing_id:
      product.listing_id ?? "",

    title:
      product.title ||
      "Untitled product",

    category:
      product.category ||
      "Gift",

    subcategory:
      product.subcategory ||
      "",

    description:
      product.description ||
      "",

    price:
      product.price ?? 0,

    personalizable:
      product.personalizable ??
      false,

    personalization_options:
      toArray(
        product.personalization_options
      ),

    style:
      toArray(product.style),

    materials:
      toArray(product.materials),

    colors:
      toArray(product.colors),

    recipients:
      toArray(product.recipients),

    occasions:
      toArray(product.occasions),

    interests:
      toArray(product.interests),

    estimated_delivery_days:
      product.estimated_delivery_days ??
      null,

    rating:
      product.rating ?? null,

    review_count:
      product.review_count ?? 0,

    review_themes:
      toArray(product.review_themes),

    match_level:
      matchLevel,

    reason:
      aiRecommendation?.reason ||
      "This product matches several parts of your shopping request.",

    requirements_met:
      Array.isArray(
        aiRecommendation?.requirements_met
      )
        ? aiRecommendation.requirements_met
        : [],

    requirements_not_met:
      Array.isArray(
        aiRecommendation?.requirements_not_met
      )
        ? aiRecommendation.requirements_not_met
        : [],

    review_insight:
      aiRecommendation?.review_insight ||
      ""
  };
}


// ============================================================
// HEALTH CHECK
// ============================================================

app.get(
  "/health",
  (req, res) => {
    res.status(200).json({
      status: "healthy",

      service:
        "Etsy AI Shopping Decision Assistant",

      products_loaded:
        products.length,

      timestamp:
        new Date().toISOString()
    });
  }
);


// ============================================================
// DATASET INFORMATION
// ============================================================

app.get(
  "/api/dataset-info",
  (req, res) => {
    res.json({
      dataset:
        "Synthetic Etsy-style listings",

      product_count:
        products.length,

      real_etsy_data:
        false
    });
  }
);


// ============================================================
// RECOMMENDATION ENDPOINT
// ============================================================

app.post(
  "/api/recommend",
  async (req, res) => {
    try {

      // ------------------------------------------------------
      // VALIDATE SHOPPER REQUEST
      // ------------------------------------------------------

      const shopperRequest =
        typeof req.body?.request ===
        "string"
          ? req.body.request.trim()
          : "";


      if (!shopperRequest) {
        return res
          .status(400)
          .json({
            error:
              "Please describe what you're looking for."
          });
      }


      if (
        shopperRequest.length < 12
      ) {
        return res
          .status(400)
          .json({
            error:
              "Please add a little more detail about the gift you're looking for."
          });
      }


      // ------------------------------------------------------
      // STEP 1:
      // EXTRACT SHOPPING CRITERIA
      // ------------------------------------------------------

      const extractionText =
        await callGemini(
          EXTRACTION_PROMPT,
          `
SHOPPER REQUEST:

${shopperRequest}
          `.trim()
        );


      const extraction =
        parseJSONResponse(
          extractionText
        );


      const criteria =
        extraction?.criteria &&
        typeof extraction.criteria ===
          "object"
          ? extraction.criteria
          : {};


      // ------------------------------------------------------
      // CLARIFICATION
      // ------------------------------------------------------

      if (
        extraction?.needs_clarification ===
        true
      ) {
        return res.json({
          needs_clarification:
            true,

          clarifying_question:
            extraction.clarifying_question ||
            "Could you tell me a little more about what you're looking for?"
        });
      }


      // ------------------------------------------------------
      // STEP 2:
      // SEARCH PRODUCT DATASET
      // ------------------------------------------------------

      const candidates =
        searchProducts(
          criteria,
          extraction?.search_terms || []
        );


      console.log(
        `Found ${candidates.length} candidate products.`
      );


      if (
        candidates.length === 0
      ) {
        return res
          .status(404)
          .json({
            error:
              "No suitable products were found for this request."
          });
      }


      // ------------------------------------------------------
      // STEP 3:
      // ASK GEMINI TO COMPARE CANDIDATES
      // ------------------------------------------------------

      const comparisonInput = `
SHOPPER'S ORIGINAL REQUEST:

${shopperRequest}


STRUCTURED SHOPPING CRITERIA:

${JSON.stringify(
  criteria,
  null,
  2
)}


CANDIDATE PRODUCTS:

${JSON.stringify(
  candidates,
  null,
  2
)}
      `.trim();


      const comparisonText =
        await callGemini(
          COMPARISON_PROMPT,
          comparisonInput
        );


      const comparison =
        parseJSONResponse(
          comparisonText
        );


      const aiRecommendations =
        Array.isArray(
          comparison?.recommendations
        )
          ? comparison.recommendations
          : [];


      // ------------------------------------------------------
      // CREATE CANDIDATE MAP
      // ------------------------------------------------------

      const candidateMap =
        new Map();


      for (
        const product
        of candidates
      ) {
        if (
          !product ||
          product.listing_id ===
            undefined ||
          product.listing_id ===
            null
        ) {
          continue;
        }

        candidateMap.set(
          String(product.listing_id),
          product
        );
      }


      // ------------------------------------------------------
      // STEP 4:
      // VERIFY GEMINI RECOMMENDATIONS
      // ------------------------------------------------------

      const recommendations = [];

      const usedIds =
        new Set();


      for (
        const aiRecommendation
        of aiRecommendations
      ) {
        if (!aiRecommendation) {
          continue;
        }


        const listingId =
          String(
            aiRecommendation
              .listing_id ?? ""
          );


        if (!listingId) {
          continue;
        }


        const product =
          candidateMap.get(
            listingId
          );


        // Ignore hallucinated/invalid IDs.
        if (!product) {
          console.warn(
            `Gemini returned unknown listing ID: ${listingId}`
          );

          continue;
        }


        if (
          usedIds.has(listingId)
        ) {
          continue;
        }


        const recommendation =
          buildRecommendation(
            product,
            aiRecommendation
          );


        if (!recommendation) {
          continue;
        }


        usedIds.add(listingId);

        recommendations.push(
          recommendation
        );


        if (
          recommendations.length === 3
        ) {
          break;
        }
      }


      // ------------------------------------------------------
      // FALLBACK
      //
      // If Gemini returned fewer than three valid IDs,
      // fill remaining positions with real dataset products.
      // ------------------------------------------------------

      if (
        recommendations.length < 3
      ) {
        for (
          const product
          of candidates
        ) {
          if (!product) {
            continue;
          }


          const listingId =
            String(
              product.listing_id ?? ""
            );


          if (!listingId) {
            continue;
          }


          if (
            usedIds.has(listingId)
          ) {
            continue;
          }


          const recommendation =
            buildRecommendation(
              product,
              null
            );


          if (!recommendation) {
            continue;
          }


          usedIds.add(listingId);

          recommendations.push(
            recommendation
          );


          if (
            recommendations.length === 3
          ) {
            break;
          }
        }
      }


      // ------------------------------------------------------
      // FINAL SAFETY CHECK
      // ------------------------------------------------------

      const safeRecommendations =
        recommendations
          .filter(
            recommendation =>
              recommendation &&
              typeof recommendation ===
                "object"
          )
          .slice(0, 3);


      if (
        safeRecommendations.length ===
        0
      ) {
        throw new Error(
          "No valid recommendations could be created."
        );
      }


      console.log(
        `Returning ${safeRecommendations.length} recommendations.`
      );


      // ------------------------------------------------------
      // RESPONSE
      // ------------------------------------------------------

      return res.json({
        needs_clarification:
          false,

        original_request:
          shopperRequest,

        criteria,

        recommendations:
          safeRecommendations
      });

    } catch (error) {

      // ------------------------------------------------------
      // ERROR HANDLING
      // ------------------------------------------------------

      console.error(
        "Recommendation error:"
      );

      console.error(error);


      const status =
        Number(
          error?.status ||
          error?.code
        );


      if (status === 429) {
        return res
          .status(503)
          .json({
            error:
              "The AI service is receiving too many requests right now. Please wait a moment and try again."
          });
      }


      if (status === 503) {
        return res
          .status(503)
          .json({
            error:
              "The AI service is temporarily unavailable. Please try again in a moment."
          });
      }


      return res
        .status(500)
        .json({
          error:
            "We couldn't complete your recommendation right now. Please try again."
        });
    }
  }
);


// ============================================================
// FRONT-END FALLBACK
// ============================================================

app.get(
  "*",
  (req, res) => {
    res.sendFile(
      path.join(
        __dirname,
        "public",
        "index.html"
      )
    );
  }
);


// ============================================================
// START SERVER
// ============================================================

app.listen(
  PORT,
  "0.0.0.0",
  () => {
    console.log(
      "=========================================="
    );

    console.log(
      "Etsy AI Shopping Decision Assistant"
    );

    console.log(
      `Running on port ${PORT}`
    );

    console.log(
      `Products loaded: ${products.length}`
    );

    console.log(
      `Gemini model: ${GEMINI_MODEL}`
    );

    console.log(
      `Gemini API configured: ${Boolean(
        GEMINI_API_KEY
      )}`
    );

    console.log(
      "=========================================="
    );
  }
);